---
- name: Verify AIDE on RHEL8 node 1
  import_tasks: aide-verify.yml
  when: inventory_hostname_short == "node1"

- name: Verify gpg on RHEL 8 node 2
  import_tasks: gpg-verify.yml
  when: inventory_hostname_short == "node2"

- name: Verify audit on RHEL 8 node 3
  import_tasks: audit-verify.yml
  when: inventory_hostname_short == "node3"

- name: Verify firewalld on RHEL 8 node 4
  import_tasks: firewalld-verify.yml
  when: inventory_hostname_short == "node4"

- name: Verify ipsec on RHEL 8 node ipsec1
  import_tasks: ipsec-verify.yml
  when: inventory_hostname_short == "ipsec1"

- name: Verify ipsec on RHEL 8 nodes ipsec2
  import_tasks: ipsec-verify.yml
  when: inventory_hostname_short == "ipsec2"

- name: Verify idm and clients
  import_tasks: idm-verify.yml
  when: inventory_hostname_short == "idm"

- name: Verify crypto on RHEL 8 on node 10
  import_tasks: crypto-verify.yml
  when: inventory_hostname_short == "node10"

- name: Verify session recording on RHEL 8 node 11
  import_tasks: sessionrecording-verify.yml
  when: inventory_hostname_short == "node11"

- name: Verify OpenSCAP lab on openscap
  import_tasks: openscap-verify.yml
  when: inventory_hostname_short == "openscap"
