---
- name: Verify AIDE on RHEL8 node 1
  import_tasks: aide-verify.yml
  when: inventory_hostname_short == "node1"

- name: Verify gpg on RHEL 8 node 2
  import_tasks: gpg-verify.yml
  when: inventory_hostname_short == "node2"

- name: Verify audit on RHEL 8 node 3
  import_tasks: audit-verify.yml
  when: inventory_hostname_short == "node3"

- name: Verify firewalld on RHEL 8 node 4
  import_tasks: firewalld-verify.yml
  when: inventory_hostname_short == "node4"

- name: Verify ipsec on RHEL 8 nodes 5
  import_tasks: ipsec-verify.yml
  when: inventory_hostname_short == "node5"

- name: Verify ipsec on RHEL 8 nodes 6
  import_tasks: ipsec-verify.yml
  when: inventory_hostname_short == "node6"
