---
hosts: all
become: yes

- name: Verify bastion for selinux-policy workshop
  hosts: bastions
  become: true
  gather_facts: False
  tasks:
  - name: Check if all  packages are installed
    package:
      state: present
      name: "{{ item }}"
    loop:
      - selinux-policy-devel
      - ansible
      - policycoreutils
      - policycoreutils-python-utils
      - audit
      - git
      - setools-console
      - selinux-policy-doc
      - policycoreutils-newrole
      - setroubleshoot-server
      - make
      - gcc-c++
      - rpm-build
      - libcurl-devel
    check_mode: yes

  - name: Check if SELinux is in Enforcing state
    selinux:
      policy: targeted
      state: enforcing
    check_mode: yes
