- name: Retrieve node 7 DNS name.
  hosts: node7.*
  become: yes
  tasks:
    - package:
        name: bind-utils
        state: present
    - command: dig +short +onesoa -x "{{ ansible_default_ipv4.address }}"
      register: dig_out
    - name: Export node 7 name.
      set_fact:
        node_dns_name: "{{ dig_out.stdout_lines[0][:-1] }}"
      delegate_facts: yes
      delegate_to: "{{ item }}"
      with_items: "{{ groups.all }}"

- name: Set IPA server and client variables
  hosts:
    - node7.*
    - node8.*
    - node9.*
  become: yes
  tasks:
    - name: Set variables.
      set_fact:
        ipaserver_domain: example.com
        ipaserver_realm: EXAMPLE.COM
        ipaserver_setup_dns: no
        ipaserver_auto_forwarders: no
        ipaadmin_password: 'r3dh4t1!'
        ipadm_password: 'r3dh4t1!'
        ipaclient_mkhomedir: yes
        ipaclient_no_dns_lookup: yes
        # ipaclient_force: yes
        ipaclient_servers:
          - "{{ node_dns_name }}"


- name: Deploy role ipaserver to node7
  hosts: node7.*
  become: yes
  roles:
    - role: ipaserver
      state: present

- name: Deploy role ipaclient to nodes 8 and 9
  hosts:
    - node8.*
    - node9.*
  become: yes
  roles:
    - role: ipaclient
      state: present
