- name: Step 005 Post Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 005 Post Software"
    - name: print out user.info
      agnosticd_user_info:
        msg: "{{ item }}"
      loop:
        - ""
        - "First open the SSH connection with port forwarding, as the following:"
        - ""
        - "ssh -L 5901:localhost:5901 -F {{hostvars.localhost.output_dir}}/{{ env_type }}_{{ guid }}_ssh_conf {{ remote_user }}@bastion"
        - "ssh -L 5901:localhost:5901 -F {{hostvars.localhost.output_dir}}/{{ env_type }}_{{ guid }}_ssh_conf {{ student_name }}@bastion"
        - ""
        - "Then run the VNC client using localhost and selecting the display number one:"
        - ""
        - "vncviewer localhost:1"
        - ""
        - "Use the following password: {{ student_password | d(hostvars[groups.bastions.0].student_password) }}"

    - name: print out user.data
      agnosticd_user_info:
        data:
          USERNAME: "{{ student_name }}"
          PASSWORD: "{{ student_password | d(hostvars[groups.bastions.0].student_password) }}"
          BASTION_IP_ADDRESS: "{{ student_password | d(hostvars[groups.bastions.0].public_ip_address) }}"
          OPENSCAP_IP_ADDRESS: "{{ student_password | d(hostvars[groups.openscap.0].public_ip_address) }}"
          IDMSERVER_IP_ADDRESS: "{{ student_password | d(hostvars[groups.idmserver.0].public_ip_address) }}"
          # GROUPS: "{{ groups }}"

- name: Verify playbook execution
  hosts: all
  become: true
  roles:
    - role: rhel-security-verification

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
