- name: Step 005 Post Software
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: "Step 005 Post Software"

    - name: print out user.info
      agnosticd_user_info:
        msg: "{{ item }}"
      loop:
        - "OpenSCAP exercise. How to connect to VNC server using SSH port forwarding:"
        - ""
        - "First open the SSH connection with port forwarding, as the following:"
        - ""
        - "ssh -L 5901:localhost:5901 -F {{hostvars.localhost.output_dir}}/{{ env_type }}_{{ guid }}_ssh_conf {{ remote_user }}@openscap"
        - ""
        - "Then run the VNC client using localhost and selecting the display number one:"
        - ""
        - "vncviewer localhost:1"
        - ""
        - "Use the following password: {{ remote_desktop_password }}"

- name: PostSoftware flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Post-Software checks completed successfully"
