---
- name: Step 004 Environment specific Software
  hosts: localhost
  gather_facts: False
  become: false
  tasks:
    - debug:
        msg: "Software tasks Started"

- name: Deploy Roles if infra_workloads defined
  hosts:
    - nodes
  gather_facts: false
  run_once: false
  become: yes
  tags:
    - infra_workloads
  tasks:
  - name: apply infra workloads roles on nodes
    when:
    - infra_workloads|d("")|length > 0
    block:
      - name: Apply role "{{ workload_loop_var }}" on nodes
        include_role:
          name: "{{ workload_loop_var }}"
        vars:
          ACTION: "provision"
        loop: "{{ infra_workloads.split(',')|list }}"
        loop_control:
          loop_var: workload_loop_var

- name: Configure graphical mode for OpenSCAP and IdM
  hosts:
    - openscap
    - idmserver
  become: true
  roles:
    - role: rhel-graphical

- name: Configure OpenSCAP
  hosts: openscap
  become: yes
  tasks:
    - name: Setup OpenSCAP
      import_tasks: openscap.yml

- name: Configure AIDE
  hosts: aide
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup AIDE
      import_tasks: aide.yml

- name: Configure gpg
  hosts: gpg
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup GPG
      import_tasks: gpg.yml

- name: Configure audit
  hosts: audit
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup AUDIT
      import_tasks: audit.yml

- name: Configure firewalld
  hosts: firewalld
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup firewalld
      import_tasks: firewalld.yml

- name: Configure IPSEC
  hosts: ipsec
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml
    - name: Setup IPSEC
      import_tasks: ipsec.yml

- name: Configure IdM
  import_playbook: idm.yml

- name: Configure Crypto Policies
  hosts: cryptopolicies
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup Crypto Policies
      import_tasks: crypto.yml

- name: Configure Session Recording
  hosts: sessionrecording
  become: yes
  tasks:
    - import_tasks: fix-authorized_keys.yml

    - name: Setup Session Recording
      import_tasks: sessionrecording.yml

- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - post_flight_check
  tasks:
    - debug:
        msg: "Software checks completed successfully"
