---
# vars file for firewalld

remote_user: ec2-user

TRACK_1_LABEL: "lab1_introduction"
TRACK_2_LABEL: "lab2_openscap"
TRACK_3_LABEL: "lab3_profiles"
TRACK_4_LABEL: "lab4_ansible"
TRACK_5_LABEL: "lab5_oval"
CACC_LOCAL: "/tmp/complianceAsCode"
